### ISSUE TITLE
Geomantic Sorcerer Kit

### ISSUE THREAD

**Issue by AnOpenHeresy** [Bubb13/Bubbs-Spell-Menu-Extended#5]
Spells don't display when using https://www.gibberlings3.net/mods/kits/geomantic/

**Comment by Bubb13** [comment]
Everything seems to work on my end. What version of EEex / the spell menu were you using? Uploading WeiDU.log, (it's next to the game's exe), and some screenshots of the problem would help track this down.

**Comment by AnOpenHeresy** [comment]
I use the latest versions, downloaded 2/3 days ago. Unfortunately I don't have screenshots, just no spells, when I uninstalled the bobbs spell menu the spells appeared in the standard ui. I don't have logs either because they are already overwritten. If it can help somehow I can install again.

**Comment by Bubb13** [comment]
You were using the released versions, right? EEex's master branch can be unstable.

Could you try a clean install with the following versions and see if the problem persists:
[EEex](https://github.com/Bubb13/EEex/releases/tag/v0.9.8-alpha)
[Bubbs-Spell-Menu-Extended](https://github.com/Bubb13/Bubbs-Spell-Menu-Extended/releases/tag/v4.5.1)
[Geomantic_Sorcerer](https://github.com/Gibberlings3/Geomantic_Sorcerer/releases/tag/v7)

**Comment by AnOpenHeresy** [comment]
I'll give it a try. I used VERSION 0.9.8 BTW
![s1](https://user-images.githubusercontent.com/51825875/188004570-9c4f9707-8caf-442b-8fc8-65dc9c80d60b.jpg)
![Baldr059](https://user-images.githubusercontent.com/51825875/188004606-ac70eb50-b4df-4d2c-9de3-340bb8f39e57.png)
[Setup-bubb_spell_menu_extended.txt](https://github.com/Bubb13/Bubbs-Spell-Menu-Extended/files/9473108/Setup-bubb_spell_menu_extended.txt)

**Comment by Bubb13** [comment]
Do you have the WeiDU.log from that install?

The install order might have been wrong; I notice that the spell menu hasn't adjusted to match DragonspearUI++, which means it was installed before DragonspearUI++ instead of after it.

The spell menu appears crushed like what you show in your screenshot if an error occurs when it is opening. Could you please download the attached zip, extract RUN.bat so that it sits next to your game's exe, and:
1) Run RUN.bat.
2) Open the spell menu, observe the bug, then exit the game normally.
3) Upload log.txt here, (it should be next to your game's exe). That log should let me see the error that's occuring.

[RUN.zip](https://github.com/Bubb13/Bubbs-Spell-Menu-Extended/files/9474052/RUN.zip)

**Comment by AnOpenHeresy** [comment]
[log.txt](https://github.com/Bubb13/Bubbs-Spell-Menu-Extended/files/9478746/log.txt)
[WeiDU.log](https://github.com/Bubb13/Bubbs-Spell-Menu-Extended/files/9478751/WeiDU.log)
[WeiDU-PI-Global.log](https://github.com/Bubb13/Bubbs-Spell-Menu-Extended/files/9478752/WeiDU-PI-Global.log)

**Comment by Bubb13** [comment]
Thanks. That bug was introduced to EEex's master branch after v0.9.8-alpha was released — I fixed it yesterday. Since master is the only version I can see that had this bug, you must have downloaded master instead of the release.

"Code => Download ZIP" gives you the master version of repository, which includes changes that may be unstable / unfinished. Use the "Releases" panel on the right side of the repo's main screen to download EEex; this goes for most mods that use releases on GitHub.

I still don't know why the spell menu failed to match DragonspearUI++'s skin though, the install order looks correct.

**Comment by AnOpenHeresy** [comment]
![brave_p08RAdOWSD](https://user-images.githubusercontent.com/51825875/188209692-0d3ce3d8-5aa8-4b12-afb8-8dc96e6065a1.png)
There are only tags available, that's why I previously downloaded via code -> zip I don't see the "Releases" version as in "Bubbs-Spell-Menu-Extended"
![brave_p19Z4KyysR](https://user-images.githubusercontent.com/51825875/188210140-384322f1-249c-43f6-bb64-bc553043d3f5.png)

**Comment by Bubb13** [comment]
I see. That does make it a little confusing; maybe it does that because all of the EEex releases are marked as "Pre-release".

Even though it doesn't show any releases on the main page, if you click the "Releases" header it will take you to the releases page, which lists all of the different versions.

**Comment by AnOpenHeresy** [comment]
ok then I download EEex-0.9.8-alpha.zip version and reinstall the whole installation it will take about 3h, thanks for your help

**Comment by AnOpenHeresy** [comment]
After reinstallation I can say that everything works! Thank you!

**Comment by Bubb13** [comment]
Great, glad everything has been resolved!
